language: node_js
node_js:
- 'stable'
sudo: false
dist: trusty
before_install:
- wget -O arduino.tgz https://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
- tar -xf arduino.tgz
- mkdir -p arduino-1.8.1/hardware/esp8266com/
- git clone https://github.com/esp8266/Arduino.git arduino-1.8.1/hardware/esp8266com/esp8266
- cd arduino-1.8.1/hardware/esp8266com/esp8266/tools
- python2 get.py
- cd -
script:
- ARDUINO=`pwd`/arduino-1.8.1 npm run build
